### ISSUE TITLE
Random responses not working as expected

### ISSUE THREAD

**Issue by glass-ships** [anthonysSlab/pot_rust#1]
perhaps @anthonysSlab could expand a bit on the specifics?

**Comment by slbsh** [comment]
alrighty mr Glass

## **Expected Behaviour:**
Bot responds with 1 in X chance per message. Chance set through config like this:
```toml
[Reply]
chance =  16  # currently set like this, any int works
```
this is loaded into the `Conf` struct in `config.rs` and then a Brenoulli distribution is initalized from it in `replies.rs`. That is used for the weighted randomness.

## **Current Behaviour:**
Bot replies with like 1 in 3 or 1 in 2 chance, that doesnt really change upon modifying config, or the variable directly.
